<GameStartMenu>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: 10

        Label:
            id: displaymenunameLabel
            text: 'Game Start Menu'
            size_hint: 1, .3
            color: 1, 0, 0, 1

        Button:
            text: 'Back to Main Menu (For debugging)'
            background_color: (0.9,0.1,0.1,53)
            size_hint: (1, 0.25)
            on_press: root.manager.current = 'mainmenu'
