# About Display
# Back to Main Menu
<AboutMenu>:
    HeaderLabel:
        text: 'About Menu'
        pos_hint: {"x": .01, "y": .94}
    Label:
        id: abouttextLabel
        text: 'A-Moll \r\n \r\n Our team consist of Artem, Marcell, Oliver, Lorenz and Ludwig: A-Moll \r\n But we are not a sad minor scale! ;)'
        pos_hint: {"x": .01, "y": .48}
        size_hint: ( .98, .16)

    BackToMenuButton:
        pos_hint: {"x": .01, "y": .01}